-- WorkFolio application schema
-- Run this in Supabase Dashboard -> SQL Editor.
-- RLS is enabled. The server-side service-role API can access these tables;
-- public users should not receive direct table access.

create table if not exists public.inquiries (
  id bigint generated by default as identity primary key,
  ref_code text not null unique,
  full_name text not null,
  email text not null,
  phone text not null,
  contact_method text not null default 'WhatsApp'
    check (contact_method in ('WhatsApp', 'Viber', 'Email', 'Phone')),
  profession text not null default 'General Professional',
  package_name text not null default 'Professional',
  selected_addons jsonb not null default '[]'::jsonb,
  total_price numeric(12,2) not null default 6500,
  custom_domain text not null default '',
  notes text not null default '',
  status text not null default 'New'
    check (status in ('New', 'Assets Received', 'In Progress', 'Reviewing', 'Live', 'Completed')),
  created_at timestamptz not null default now()
);

create index if not exists inquiries_created_at_idx
  on public.inquiries (created_at desc);
create index if not exists inquiries_status_idx
  on public.inquiries (status);

create table if not exists public.faqs (
  id bigint generated by default as identity primary key,
  category text not null
    check (category in ('General', 'Domain & Hosting', 'Payments', 'CV & Media', 'Guarantee')),
  question text not null,
  answer text not null,
  is_published boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  client_name text not null,
  profession text not null,
  rating integer not null default 5 check (rating between 1 and 5),
  review_text text not null,
  portfolio_url text,
  verified boolean not null default false,
  is_published boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.portfolio_samples (
  id bigint generated by default as identity primary key,
  name text not null,
  title text not null,
  industry text not null,
  subdomain text not null unique,
  avatar_url text not null default '',
  cover_url text not null default '',
  experience_years text not null default '',
  location text not null default '',
  bio text not null default '',
  key_skills jsonb not null default '[]'::jsonb,
  certifications jsonb not null default '[]'::jsonb,
  photo_count integer not null default 0,
  video_count integer not null default 0,
  has_custom_domain boolean not null default false,
  featured boolean not null default false,
  is_published boolean not null default true,
  created_at timestamptz not null default now()
);

-- Do not expose these tables directly through the browser.
alter table public.inquiries enable row level security;
alter table public.faqs enable row level security;
alter table public.reviews enable row level security;
alter table public.portfolio_samples enable row level security;

-- Keep the public API backed by the server-side service role for now.
-- Authentication and narrowly-scoped policies will be added before launch.
